baseURL = 'http://michaelacheong.com/'
languageCode = 'en-au'
title = 'Michaela Cheong'
theme = 'PaperMod'

paginate = 5
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true
googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Michaela Cheong"
description = "A lil' digital garden."
keywords = [ "Digital Garden", "Blog", "Portfolio", "PaperMod" ]
author = "Me"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "2006-01-02"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowWordCount = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
hideAuthor = true
showtoc = false
tocopen = false
fontbody = "Avara_Bold"
fontcode = "Space Mono"


  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "Michaela Cheong"
  subtitle = "I follow Jesus."
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archive"
    url = "archive"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Michaela's digital garden"
  Content = "A place to grow (in Christ)"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/vitamickey"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/michaelacheong/"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/vitamickey/digital-garden/tree/main/content"
  Text = "Suggest changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]


[[menu.main]]
identifier = "nowmenu"
name = "now"
url = "/posts/now/"
weight = 10

[[menu.main]]
identifier = "archive"
name = "archive"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 40



[outputs]
home = ["HTML","RSS","JSON"]