baseURL = "http://michaelacheong.com/"
title = "Michaela"
languageCode = "en-au"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true
googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[permalinks]
  posts = '/:filename/'

[params]
env = "production"
title = "Michaela's Digital Garden"
description = "A lil' digital garden."
keywords = [ "Digital Garden", "Blog", "Portfolio", "PaperMod", "Christian" ]
author = "Me"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "Jan 02, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowWordCount = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false
fontheader = 'Avara_Bold'
fontbody = 'EB Garamond'
fontcode = 'Xanh Mono'

  [params.assets]
  favicon = "img/favicon.ico"
  favicon16x16 = "img/favicon-16x16.png"
  favicon32x32 = "img/favicon-32x32.png"
  apple_touch_icon = "img/apple-touch-icon.png"
  safari_pinned_tab = "img/apple-touch-icon.png"

  [params.label]
  text = "Home"
  icon = "img/apple-touch-icon.png"
  iconHeight = 50

  [params.profileMode]
  enabled = false
  title = "Michaela Cheong"
  subtitle = "I follow Jesus."
  imageUrl = "img/cat-with-book.jpg"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "Cat reading a book"

    [[params.profileMode.buttons]]
    name = "Archive"
    url = "archive/"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags/"

  [params.homeInfoParams]
  Title = "I am Michaela, and this is my digital garden."
  Content = "A place to grow (in Christ)."

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/vitamickey"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/michaelacheong/"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/vitamickey/digital-garden/tree/main/content"
  Text = "Suggest changes to this post"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"


[[menu.main]]
identifier = "nowmenu"
name = "now"
url = "now/"
weight = 10

[[menu.main]]
identifier = "archive"
name = "archive"
url = "archives/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "tags"
url = "tags/"
weight = 30

[[menu.main]]
identifier = "search"
name = "search"
url = "search/"
weight = 40

[outputs]
home = ["HTML","RSS","JSON"]